### ISSUE TITLE
Flickering when picking voxels

### ISSUE THREAD

**Issue by jjhembd** [CesiumGS/cesium#11841]
### What happened?

Mouseover picking sometimes jumps or flickers even when the cursor is relatively stable near the middle of a voxel cell.

See this screen recording from @ggetz. Note: so far the bug has only been observed on a Mac.

https://github.com/CesiumGS/cesium/assets/41167620/68e007ea-4dfd-4764-9e67-c02502bce37d

### Reproduction steps

1. Load the below Sandcastle (on a Mac)
2. Zoom on one corner of the voxel
3. Move the mouse across adjacent voxels

### Sandcastle example

http://localhost:8080/Apps/Sandcastle/index.html#c=tRiLbts48ld4vmIht4ry6gIHJw0uzabXAElT1Gmu27hoaYm2uKUkH0k5dgL/+w2HlETayaa9R5FC1nBenPcorUqlyZyzWybJK1KyW3LCFK+L5Bph0aiX4vtJVWrKSyZHvZjcj0pCxlSxc7pkctCQnBV0yuQSgclEVsV7Wc15xuSxWpZpZIhIg3vFBbugsyGTc54yR9ngI/FHKRxJSzSuucguqqwWDE97x0oxrbav2ELXkqntdxSeVJxSqfOzs1Gvbxngox8HWr/n6Xej+4QKxfBoyqq0ykKY5gUTcG0fRkteUM2rsgOu+gejclSmaM17olJWspiktGCSkhUY1loYkfAwydi4ng7z6vaNBCz1nskhA/IMcLWsmcdOpZLqND+pRLXmIgRFVvSkLlOjEwEbpiwzVriohebGztfVgonGtpHK6Yz1rQ91zlWCAOCMz4MWnMHVSwUs1ZpUMC78ouV+9DIm5q/fEZXmMoB/A3FjtBv1vnSHejmzh47TBdM0o5peATy5Pj156eGmVTGrSlbqq0eITnyE5M355fHV/p7H4KtgcyZOqrrUQL0PBytjp6fMk8xkpSujaSLZv2qm9G8gDDi0BsagrGbmtxqVzpCN5zXwOzeCY/z5yT5+t4/PGAqOFL1GCJ+QqCUiR682lHcCCJEMYrskdZmxCURkhlddWS5WfOCxNR8edGjmcg0CuuRm54t3LGmZVcWQMYhFK9nq/tzjnyzD1wV5YS/6MPiTxx4dDjDQAAGyTvUHFGmgxthRxyFGZWNPp76zm7MGuK3gyvhKVWLOopuG/ReDuApT4z+SZ83fBB/VeQIlxzJ4Vxdjk7csi0IFm7vOTWQ1IRjY5c+MeedxSHNalh2PhxJnynSbC4gXmTv010zul483oqJ6f+9YSrqMPB2fB+IaS0+ALhJMkzsg3zmAx2GoLbl78aKN0hZ7abGXIfYSIB62h7+w+IsQfwGQAL+5k2ByxuQnIFqQbRIFxt0iu/b6mwS/A8FyjWD5ZwSfgeBujeCuIehItrctUQ7oec0g7hsFn5Od5FcgaOSb9/32/DO+720Izz1nm5grocP5QRdt6muSfjfZWRO1yVoYQye/bsBTFyF+c8FG/FaJKI8JJAdUNZAQBy0ptINlxaFGLZrqYf/dPVk/HgAtNpS0ebb389ahYpZTiwPESDURFbTPhuMLY5TwMm3e3NgLhflhKL5gFTOGkq4g/yDlbkc5lYyVP0O719GORc1+hnTfkHqmaGlX9sfK6ymuwrY8mw5q7Tlz/dKVlCenDq+I4sHQDBtYv15ffoI26g08aa001NKcZusz6Yl3EmFJmEg6hZDRFmbmwAH5Nq941p5cwNQavXEvZ+Ws1mSi8BlDnFbwmt4VXwsY/AREBZOcClK4H258bIvPnKX7tqi/q2RBTSaV+IPfsciwsW9gdyciQeRE1XJCU2aJuticmDoMMT+Z1Mr0w4Iuoh2TX1mlI09MjCoKPs31b1wybGanJ/11RojAy6nNbxvQmFPI34tsDrFg2vKZTdM1ZduTAx9f0WL2GIV3dhCYKmVCNI2nISlc70pc3kzHoGOjeifSjUVO4CtSf1VMwNVZhsPDL7+EGvkIQzwIekbj0MQzNl9ErX4x6htBcevHTR3YoMW8efwmtEsmwmAteEJ+K/u/E+Xy9htuJnXJoZ8WatDIDq026FQyI0K7t320ZJiNZ++u4taHFMrLgGyZmu/kxOt8rbH/V5xX67tUk5eSL4KaD+8vsTkNUyqYX1269QTPTwUzia/C7fNUCD5TUCaSf/5j+LeXCWQeL+riA814reL/CyquoGGhm9sKyQuu+Rw3MFwNZw1EJTTLUHF/Lw+IImf3phwP2l9ONb+YDoI3h+BZeOC/WH+0Goe6QselMHJr9L4tOW5rXcP7g2uNVRw3ZQxbuD3uxdB/l1fVa+hMGXAYznImWbRGPg5O3YcH02bs+r2D4RMEDPS7TKz3jWFqeuxwBjX4dA7R8NYiRdbeKS3nVBkmrrWZLwPZCQwHIBoy0szuVVqbMDLDtouo18sz8E1vHXnU22RkC+DTPHBfNuTuEmbTwPw/xpIfdStoUc2RQbB9FhVUlveV4ogDFc4hJazMGvDGcgJVqAs80APDKwpY2WJoKvJfnD3dBhq1LPprW2qzm4aLMdbq2C/cMakkBxVZ1sTB62phP5g0rD2NbwgQLGOYJc0Yczn+AypQgqVERQ/wSVIDkX3Iw1mEE580h/Y6635LOMxJ8u3VxTmw/marGrEMcDV5dr9YxbjUPLtfrmJchp7d362++ZvzdEyvUR3/AsbfMAbBRK6XUftZxN/P0sc+7SRJ0vEM9TZtQOmlgByh6fcp3qyJNNskdHWiFIKGkM/l1A3FvlOCSSuweleErJ4eoolKV9fhOmGHMR8HW0/3f5jUmtsQe7GBC3z8WApjS7m4/Dg8/XpxeX1qkHtx7xBNcmTk/p3DTiw1qaUAO25rBozBz2p7XIMFdZIqZ9G/GpN+YIjsgrgz6RbacoCujWAyc3/NhLBqGQQFw7HJuAKZywEMUOYb4tZYVOl317pnUNrBKQOym+bt//00f4CtceoPcLzlmc6BH2um+pyZqcqHbN7rNue62SAKKqe83BJsolGtRpXD7caqhxmfE569euCjMEkFVQpOJrUQQ5iHR72jw23AD8hgTjW3vpwzCdcwKPnu0bkFQrAfbsPrJpWuKjGmIAQd28E7x7mj9cOwMB+FWd3IeZgMk/Sow2m1cs9/Aw

### Environment

Browser:
CesiumJS Version: 1.114, commit https://github.com/CesiumGS/cesium/pull/11828/commits/ca7a8b8757161a7846f0054110e4d37c6e9c6b70
Operating System: Mac OS

**Comment by jjhembd** [comment]
The problem behavior will be in the `main` branch after https://github.com/CesiumGS/cesium/pull/11828 is merged

**Comment by jjhembd** [comment]
@ggetz after https://github.com/CesiumGS/cesium/pull/11875 I observed a similar problem on Windows. I fixed a sample indexing problem at the edges of the volume, in https://github.com/CesiumGS/cesium/pull/11909/commits/4c6e7ea0cb176b73ddd8570c8e97b68bd07f26d2 (part of https://github.com/CesiumGS/cesium/pull/11909).

Can you please check if this fixes the flickering on your machine?

**Comment by ggetz** [comment]
@jjhembd I tried the deployed version from https://github.com/CesiumGS/cesium/pull/11909, and it may be less frequent, but I'm still seeing flicker:


https://github.com/CesiumGS/cesium/assets/4439461/65f0307a-5439-4b0c-87ca-bbd552e637b3

**Comment by jjhembd** [comment]
@ggetz thanks for checking! This new video will be helpful for further debugging. The Z value looks like it’s flickering clear across the whole volume.

**Comment by jjhembd** [comment]
Hi @ggetz, I'm wondering if this was fixed by https://github.com/CesiumGS/cesium/pull/12933. Can you please verify on Mac?

**Comment by jjhembd** [comment]
Here is an [updated version of the Sandcastle](https://sandcastle.cesium.com/#c=tRiLbts48ld4uWIht4qcRxc4OGlwqTe9Bkiaok5z3SZFS0u0xS0l+UjKsRP43284pCTSTjbtPYq2soYzw3k/lFal0mTO2S2T5BUp2S0ZMsXrIrlCWHSzleL7sCo15SWTN1sxub8pCRlTxc7okslBQ3Ja0CmTSwQmE1kV72U15xmTx2pZppEhIg3uJRfsnM5GTM55yhxlg4/EH6VwJC3RuOYiO6+yWjA83TpWimnVv2QLXUum+u8oPKk4oVLnp6c3Wz3LAB+9OJD6PU+/G9knVCiGR1NWpVUWwjQvmAC1fRgteUE1r8oOuOod3JQ3ZYrWvCcqZSWLSUoLJilZgWGthREJD5OMjevpKK9u30jAUu+ZHDEgzwBXy5p57FQqqU7zYSWqNRchKLJXT+oyNTIRsGHKMmOF81pobux8VS2YaGwbqZzOWM/6UOdcJQgAzvg8aMEZqF4qYKnWbgXjwi9a7kcvY2L+9jqi0igD+NcQN0a6m60v3aFezuyh43TONM2oppcAT65Ohi893LQqZlXJSn35CNHQR0jenF0cX+7veQzonHJBx4KdsTkThsM+HK6MrZ4yUTKTla6MtIlk/6qZ0r/BhcChNTIGZjUzv9VN6YzZeF9zd2mMPz/Zx+/28RnDwZGi5wjhExK1ROTo1YMKuEsIkQxivCR1mbEJRGaGKq8sJytC4Lk1Xx50aEbBBgFdc73zxTuWtMyqYsQYxKS92cr/3OOfLMPXBXlhlX0Y/Mljj44HGEiAAFmn+gNeaaDG4FHHIUZhY0+m3oGvMfyvIRSAV1O9jD+HForVpAmbYynpMrpubv9iY9fZFAKg4Mp4XVViziLH1uCswiz7j0S2HmzimOo8geplGbyri7EpASyLQh0bDedWoRqVDEz7Z/648zikOS3LjsdDOThluk0rxIuMDr01r/mV6I2oqN7fs1b1ZHweXNc4awJ0kWCa3AH5zgE8DkNpyd2LF22gt9hLi70MsZcA8bA9/IXFX4T4C4AE+I1OgskZk5+AaEH6JAqMu012rfqbBL8DwXKNYPlnBJ+B4G6N4K4h6Ej6fUuUA3peM0idRsDnZCf5FQia+837fnv+Gd/3Ni7PPWebmCuhWfpBF23Ka+rGbrKzdtUma2EMnfy6AU9dhPh9CrPwrRJRHhNIDiiOcEMcdLfQDpYVhzK3aAqQ/XP3ZAl6ALTYENLm2d7PW4eKWU4tDhAj1URU0Ikbji+MUUJl2ry5tgqF+WEovmAhNIaSrqb/IOVuRzmVjJU/Q7vX0Y5FzX6GdN+QeqZoaVf2x8prS668tjybRmztOXNt15WUJwcYr4jiwcjMLVi/Xl98gm7szU5prTTU0pxm6+Pt0DuJsCRMJJ1CyGgLMyPlgHybVzxrT85hAI7euJfTclZrMlH4jCFOK3hN74qvBcyQAqKCSU4FKdwPN4m2xWfO0n1b1N9VsqAmkxyvhGot+biGISsp8exk2Bp3YuotxPZkUivTOgu6iHZMHmWVjjx2MYoi+DTXv3HJsGmdDHu9NUaIwMupzWMbuJg7yN+LYA4+Nx381KZjKytembQnBz6+osXsMQrv7CAwScqEaBpMQ1K4HpW4/JiOQcZG9O5KN0W5C1+R+qtiAlRnGc4Zv/wSSuQjjPAg6A2N4xLP2HwRtfLFKG8ERawXN/m+QYv58bgmtEsaAiMee+L+9u7/7iqXn99wmalLDn2zUIPm7tBqg04kMwq0q95HS4ZZd/ruMm59SKGMDMi2qe3unnidrzX2/4rzan39avJP8kVQ2+H9JTahUUoF86tIt9Hg+YlgJsFVuLCeCMFnCspB8s9/jP72MoHM40VdfKAZr1X8f0HFrTUsaHNbCXnBNZ/j0obb5KyBwNqQZSi4v8oHRJGze1N2B+0vJ5pfNAfBm0PwLDzwX6w/WolDWaGzUpirNXrflhy36K7h/cG1xmqNyzWGLWiPqzT02eVl9Ro6UAYcRrOcSRatkY+DU/etwrQTu7HvYPgEAQN9LRPr/WGUml46mtGUncwhGt5apMjaO6XlnCrDxLUw8zEhG8IQAFdDRpoZvUprE0ZmqHYR9Xp5Cr7ZWke+2dpkZAvg0zxwxTbkTgmzUWD+H2PJj7qNtajmyCBYVosKKsv7SnHEgQrnkBJWZg14YwmBKtQFHsiB4RUFrGwxNBX5L86eblmNWha9tYW2WWPDPRprdewX7phUkoOILGvi4HW1sN9YGtaexNcECJYxzIxmXLkY/wEVKMFSoqIH+CSpgcge5OEswslOmkOrzrrfEg7zkHx7eX4GrL/ZqkYsA1xBnt0vVjEuL8/ul6sYl55n93erb/6SPR3TKxTHV8D4G8YdmLz1Mmq/pPh7WPrY16AkSTqeodymDSi9FJAjNP0+Rc2aSLNNQldDpRA0gnwup2749Z0STFSB1bsiZOX0EE1UuroO6oQdxnxPbD3d+2FSa25D7MUGLurxYymMLeX84uPo5Ov5xdWJQd6Ktw7RJEfm3r9z2H2lJrUUYMe+ZsAY/Kz64xosqJNUOYv+1Zj0A0NkF8SdSbfRlgN0bQSTmfvbTAirlkFQMBybjCu4czmAAcp8dtweiyr97lr3DEo7OGVAdtO8/bef5g+wNU79AY63PNM58GPN9J4zM1X5kE29bnOum02hoHLKy23BJhrFakQ57DdWPcz4nPDs1QPfkUkqqFJwMqmFGPE78ObRYR/wAzKYU43WF3MmQQ2Dku8enVkgBPthH143qXRViTGFS9CxHbxznDtaPwwL81GY1c09D5Nhkh51OK1U7vlv)

**Comment by jjhembd** [comment]
CC @mzschwartz5 if you have a chance to check on MacOS. Thanks!

**Comment by mzschwartz5** [comment]
Just played around with it for a few minutes, no flickering over here!

**Comment by jjhembd** [comment]
Thanks @mzschwartz5, that's good to hear! Closing for now.
